### ISSUE TITLE
GitHub Actions 棄用 save-state、set-output

### ISSUE THREAD

**Issue by stoneshih225** [bbinmkt-organization/event-action#4]
2022/10/11 時發布了棄用 save-state、set-output 這兩種方法, 目前只有跳出警告, 可能需要找個時間修改寫法, 感謝
2023/5/31 之後就會全面停用 [[來源]](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

**Comment by hms5232** [comment]
討論之後，由於此功能實際上沒有使用，故之後會改成有一個預設、非陣列的 Node 版本，但一樣提供參數給使用者覆蓋。
